apiVersion: apps/v1
kind: Deployment
metadata:
  name: metrics-backend
  namespace: metrics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metrics-backend
  template:
    metadata:
      labels:
        app: metrics-backend
    spec:
      containers:
        - name: backend
          image: sidya18/metrics-backend:latest
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: metrics-secrets
                  key: DATABASE_URL
