apiVersion: v1
kind: Service
metadata:
  name: metrics-grafana
  namespace: metrics
spec:
  type: NodePort
  selector:
    app: metrics-grafana
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30300
