apiVersion: apps/v1
kind: Deployment
metadata:
  name: metrics-grafana
  namespace: metrics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metrics-grafana
  template:
    metadata:
      labels:
        app: metrics-grafana
    spec:
      containers:
      - name: grafana
        image: grafana/grafana:10.2.2
        ports:
        - containerPort: 3000
        env:
          - name: GF_SECURITY_ADMIN_USER
            valueFrom:
              secretKeyRef:
                name: metrics-secrets
                key: GRAFANA_ADMIN_USER
          - name: GF_SECURITY_ADMIN_PASSWORD
            valueFrom:
              secretKeyRef:
                name: metrics-secrets
                key: GRAFANA_ADMIN_PASSWORD
        volumeMounts:
        - name: grafana-datasources
          mountPath: /etc/grafana/provisioning/datasources
        - name: grafana-dashboards
          mountPath: /etc/grafana/provisioning/dashboards
        - name: grafana-dashboard-json
          mountPath: /var/lib/grafana/dashboards
      volumes:
      - name: grafana-datasources
        configMap:
          name: grafana-datasources
      - name: grafana-dashboards
        configMap:
          name: grafana-dashboards
      - name: grafana-dashboard-json
        configMap:
          name: grafana-dashboard-json
