apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: metrics-agent
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      app: metrics-agent
  template:
    metadata:
      labels:
        app: metrics-agent
    spec:
      containers:
        - name: agent
          image: {{ .Values.agent.image }}
          env:
            - name: BACKEND_URL
              value: "http://metrics-backend:{{ .Values.backend.port }}/metrics"
