apiVersion: apps/v1
kind: Deployment
metadata:
  name: metrics-backend
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metrics-backend
  template:
    metadata:
      labels:
        app: metrics-backend
    spec:
      containers:
        - name: backend
          image: {{ .Values.backend.image }}
          ports:
            - containerPort: {{ .Values.backend.port }}
          env:
            - name: PORT
              value: "{{ .Values.backend.port }}"
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: metrics-secrets
                  key: DATABASE_URL
