apiVersion: v1
kind: Secret
metadata:
  name: metrics-secrets
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  POSTGRES_USER: {{ .Values.postgres.user | b64enc }}
  POSTGRES_PASSWORD: {{ .Values.postgres.password | b64enc }}
  POSTGRES_DB: {{ .Values.postgres.db | b64enc }}
  GRAFANA_ADMIN_USER: {{ .Values.grafana.adminUser | b64enc }}
  GRAFANA_ADMIN_PASSWORD: {{ .Values.grafana.adminPassword | b64enc }}
  DATABASE_URL: {{ printf "postgres://%s:%s@metrics-db:5432/%s?sslmode=disable" .Values.postgres.user .Values.postgres.password .Values.postgres.db | b64enc }}
