name: CD to Kubernetes

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up K8s
        run: |
          echo "${{ secrets.KUBECONFIG_DATA }}" | base64 -d > $HOME/.kube/config

      - name: Upgrade Helm release
        run: |
          helm repo add metrics-saas https://sid-romero.github.io/metrics-dashboard-saas/
          helm repo update
          helm upgrade --install metrics-saas metrics-saas/metrics-saas -n metrics --create-namespace
