name: Helm Release

on:
  push:
    branches:
      - main
    paths:
      - 'chart/**'
      - 'docs/**'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.13.2

      - name: Package chart
        run: |
          helm package chart/metrics-saas --destination docs/
          helm repo index docs --url https://sid-romero.github.io/metrics-dashboard-saas/

      - name: Commit and push chart
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: release Helm chart"
          branch: main
